root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/sik6"
bin = "tmp/main"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_unchanged = true
include_ext = ["go", "tpl", "tmpl", "html"]
follow_symlink = false

# CRITIQUE: Activer le polling pour Docker
poll = true
poll_interval = 500

stop_on_error = true
kill_delay = 500

[log]
time = true
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true