version: "2"

linters:
  enable:
    - govet
    - staticcheck

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules
    - dist
    - tmp

issues:
  exclude-use-default: false
